name: iMirAI
description: "The Smart AI for your business."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  local_auth: ^3.0.0
  local_auth_android: ^2.0.4
  local_auth_ios: ^1.1.7
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  get: ^4.7.3
  http: ^1.6.0
  awesome_snackbar_content: ^0.1.1
  flutter_html: ^3.0.0
  path_provider: ^2.1.1
  file_picker: ^10.3.8
  csv: ^6.0.0
  mobile_scanner: ^7.1.4
  change_app_package_name: ^1.5.0
  flutter_html_table: ^3.0.0
  url_launcher: ^6.3.2
  open_file: ^3.5.11
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/